### PR TITLE
* numerous updates to support versions through 1.1.0

### PR DESCRIPTION
**Pull request by freakinhippie**
* add attribute driven recipes for  acls/checks/scripts/services/watches
* add documentation in README.md for custom resources, fixes issue #2
* add option to override package sha256sum, fixes issue #22
* updated nssm dependency to v 4.0.0, fixes issue #23

Signed-off-by: Joshua Colson <joshua.colson@gmail.com>

### CODE REVIEW

**Comment by freakinhippie** [comment]
There are a few rubocop offenses that are still outstanding. Let me know how you'd like me to address them.

**Comment by vkhatri** [comment]
@freakinhippie Thank you for the PR 👍 

I will take a look those rubocop offenses later today and release a new version.

**Comment by freakinhippie** [comment]
@vkhatri Are you going to be able to release a new version?

**Comment by vkhatri** [comment]
@freakinhippie Sorry about the delay. I have released `v0.2.0`.

Will release another one shortly with travis fix etc.

**Pull request merged**
