### PR TITLE
Consul 0.6.4 Support

### PR DESCRIPTION
**Pull request by CpuID**
Version bump.

### CODE REVIEW

**Comment by CpuID** [comment]
Feel free to merge https://github.com/vkhatri/chef-consul-ng/pull/15 prior to get passing tests :)

**Comment by vkhatri** [comment]
@CpuID Sorry for the delay to get to this PR.

Could you please rebase with the master? PR now has conflicts after merging PR 13.

**Comment by CpuID** [comment]
@vkhatri I'll fix the failures shortly

**Comment by CpuID** [comment]
@vkhatri tests pass, good for review again.

**Comment by vkhatri** [comment]
@CpuID 👍

**Pull request merged**
