### PR TITLE
Allow init script to be installed for tests in kitchen-docker

### PR DESCRIPTION
**Pull request by CpuID**
When using [kitchen-docker](https://github.com/portertech/kitchen-docker) the `init_package` Ohai property is set to `sshd`. Use the standard sysvinit script in these scenarios.

### CODE REVIEW

**Comment by CpuID** [comment]
Feel free to merge https://github.com/vkhatri/chef-consul-ng/pull/15 prior to get passing tests :)

**Comment by vkhatri** [comment]
@CpuID Could you please rebase it with master? sorry for the inconvenience.

**Comment by CpuID** [comment]
@vkhatri passes in travis now.

**Comment by vkhatri** [comment]
@CpuID 👍

**Pull request merged**
