### PR TITLE
Added support for systemd service

### PR DESCRIPTION
**Pull request by rmul**
Hi Virender, 
I wanted to deploy this on Centos 7 which uses systemd, so I've written some code and created this pull request. I use chef/sugar gem to easily determine if systemd is used or upstart and then use the template based on that.

### CODE REVIEW

**Comment by vkhatri** [comment]
@rmul Thank you for the PR! Could you please look into travis failures?

**Comment by rmul** [comment]
I see I've probably forgotten to include the gem in the gemfile (https://github.com/sethvargo/chefspec/issues/336). Will look into that

**Comment by rmul** [comment]
Build passes now ;-)

**Comment by vkhatri** [comment]
@rmul LGTM, thank you for fixing the Gemfile. But chefspec is failing for me. Any idea about this error.

```ruby
    Errno::ENOENT:
        No such file or directory @ rb_sysopen - /proc/1/comm
      Shared Example Group: "consul" called from ./spec/unit/recipes/default_spec.rb:96
      # /Users/vkhatri/.rvm/gems/ruby-2.2.1/gems/chef-sugar-3.2.0/lib/chef/sugar/init.rb:28:in `read'
      # /Users/vkhatri/.rvm/gems/ruby-2.2.1/gems/chef-sugar-3.2.0/lib/chef/sugar/init.rb:28:in `systemd?'
      # /Users/vkhatri/.rvm/gems/ruby-2.2.1/gems/chef-sugar-3.2.0/lib/chef/sugar/init.rb:52:in `systemd?'
      # /var/folders/4g/vkwwhwrn56n4x7p_q3h349v00000gn/T/d20160106-8727-1nh5fae/cookbooks/consul-ng/recipes/config.rb:45:in `block (2 levels) in from_file'
```

Strange that travis is passing, but it is failing on my local environment. I will give it a try before i merge the PR.

**Comment by vkhatri** [comment]
@rmul  Seems like it has to do with mac as there is no `/proc/1/comm`. I will wait for you thoughts on it.

**Comment by rmul** [comment]
looks like chef-sugar is not suitable for mac (can reproduce on the mac of a colleague). I'll see if I can change to not using this gem..

**Comment by vkhatri** [comment]
@rmul I am glad to hear that! I will also give it a try.

**Comment by rmul** [comment]
done and chefspec (on my windows machine) no longer complains

**Comment by vkhatri** [comment]
@rmul Thanks for fixing the PR :+1: 

I will publish new version once i have HWRP examples documented.

**Pull request merged**
